hamburgrouble_api_client:
    resource: "@HamburgroubleApiBundle/Resources/config/routing.yml"
    prefix:   /

etki_hamburgrouble:
    resource: "@EtkiHamburgroubleBundle/Resources/config/routing.yml"
    prefix:   /api/v1
